[tools.black]
line-length = 88

[tools.mypy]
disallow_untyped_defs = true
disallow_any_unimported = false
ignore_missing_imports = true
ignore_missing_imports_per_module = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = false
show_error_codes = true
warn_unused_ignores = true
warn_unused_configs = true
exclude = ["venv","venv_dev","venv_prod", "migrations"]

[tools.ruff]
select = ["E", "F", "B", "I", "W", "N", "D", "UP", "A", "C4", "PT"]
line-length = 88
extend-exclude = ["venv","venv_dev","venv_prod"]
fix = true
show-fixes = true

[tool.ruff.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tools.pytest]
testpaths = "tests"
